package com.fullrandomstudio.designsystem.theme

import androidx.compose.ui.graphics.Color

val DisabledAlpha:Float = 0.38f
val Transparent = Color(0x00FFFFFF)
val Debug = Color(0xFF6E9C7B)
val NotificationLight = Color(0xFF00FFFF)

val md_theme_light_primary = Color(0xFF37474F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF546A75)
val md_theme_light_onPrimaryContainer = Color(0xFF21282C)
val md_theme_light_secondary = Color(0xFF607D8B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF607D8B)
val md_theme_light_onSecondaryContainer = Color(0xFFFFFFFF)
val md_theme_light_tertiary = Color(0xFFE95E62)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE95E62)
val md_theme_light_onTertiaryContainer = Color(0xFFFFFFFF)
val md_theme_light_error = Color(0xFFCA384F)
val md_theme_light_errorContainer = Color(0xFFCA384F)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF8F8F8)
val md_theme_light_onBackground = Color(0xFF607D8B)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF607D8B)
val md_theme_light_surfaceVariant = Color(0xFFF8F8F8)
val md_theme_light_onSurfaceVariant = Color(0xFF495E68)
val md_theme_light_outline = Color(0xFF495E68)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF546A75)
val md_theme_light_inversePrimary = Color(0xFFFFFFFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF546A75)
val md_theme_light_outlineVariant = Color(0xFF607781)
val md_theme_light_scrim = Color(0xFF000000)
